### ISSUE TITLE
Ready for a new release?

### ISSUE THREAD

**Issue by HannesSommer** [ethz-asl/libpointmatcher-release#1]
The current libpointmatcher release does not currently build on the build farm (see e.g. http://jenkins.ros.org/job/ros-indigo-libpointmatcher_binarydeb_trusty_amd64/) but the master does using the libnabo 1.6 release (see http://jenkins.ros.org/job/devel-indigo-libpointmatcher/), thanks to the current solution for (https://github.com/ethz-asl/libpointmatcher/issues/70).

I think it is a good time to issue a new release (maybe right after PR https://github.com/ethz-asl/libpointmatcher/pull/87 has been decided upon). 
It will most likely be a big improvement compared to the current state. Agreed?

**Comment by pomerlef** [comment]
yep

**Comment by HannesSommer** [comment]
Done with c10f65a45adc00aff17d47641a5617106d871495 and 787de8780aac0d7c4639469d5451d31b7256f275.
